### ISSUE TITLE
backend stats

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-monitoring#36]
In case the backend is a global backend, the writes are always 0 as the puts/gets are only displayed on the local hdd backends.

**Comment by jeroenmaelbrancke** [comment]
Does backends also have writes?
I thought backends only have puts and gets...
The issue with the global backend puts/gets are solved on the OVH setup. #42

**Comment by wimpers** [comment]
You are right ...  in the case of a backend a write is a put.
