### ISSUE TITLE
vPool IOPS are incorrect

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-monitoring#44]
vPool IOPS are incorrect (grafana/dashboard/db/vpool-overview)

There are way too many the same numbers to be correct.
![2016-07-14_11-55-04](https://cloud.githubusercontent.com/assets/8392927/16835647/fd5fca1a-49b9-11e6-8568-1a35aef19d01.png)

**Comment by jeroenmaelbrancke** [comment]
The graph stacked all the values.
Changed this back to normal and everything looks fine now.
Thx for the remark.
