### ISSUE TITLE
Make object safety chart more clear

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-monitoring#51]
Currently the object safety chart isn't clear ...
![2016-08-02_15-19-38](https://cloud.githubusercontent.com/assets/8392927/17332219/4164a7b2-58ce-11e6-9a12-b2eb8383c104.png)

Can we replace this by:
- Pie chart which displays amount of objects and their current safety (e.g. the amount of disks that can be lost before you have dataloss)  
- Line chart of fragment/objects which needs repair

**Comment by jeroenmaelbrancke** [comment]
New look for the disk safety and repair objects.

![disk_safety](https://cloud.githubusercontent.com/assets/2900612/17440408/c77a9a0e-5b2c-11e6-935d-98ad3f7fcac4.png)
![repair_objects](https://cloud.githubusercontent.com/assets/2900612/17440409/c77cb208-5b2c-11e6-8016-5a747fd3a917.png)
