### ISSUE TITLE
Option to increase frequency for a component.

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-monitoring#52]
For troubleshooting issues the current refresh interval of statistics is too large. Hence we would like the option to have a more fined grained refresh interval which can be set on a component base.

**Comment by jeroenmaelbrancke** [comment]
for the moment only statsmonkeyscheduledtask.py have this option.
You can change the interval via ansible --> roles --> statsmonkey --> vars --> main.yml --> interval

I assume you want to define this in a config file or etcd?

**Comment by wimpers** [comment]
Not sure I understand the comment. You mean you can for all stats increase the frequency (and not for a single component like voldrv xyz) or is it not for checkMK you mean? 

Yes, config in etcd would be ok. (Do know we will be using arakoon as default config mgmt store in the future as etcd fails too much). Do make sure there is an option to update statsmonkey so it retrieves the new config.

**Comment by jeroenmaelbrancke** [comment]
Everything is described in the [statsmonkey gitbook](https://openvstorage.gitbooks.io/ovs-monitoring/content/docs/statsmonkey.html).
